version: '3.6'

x-shared-environment: &commonEnv
    TZ: "America/Mexico_City"

services:
    cache_erp:
        container_name: 'cache_erp'
        image: redis:alpine
        ports:
          - "6379:6379"
        environment: *commonEnv
        networks:
          - operational_network
    sso_ereceipt:
        container_name: 'sso_ereceipt'
        build: './OPERATIONAL/sso'
        ports:
          - '10100:10100'
        environment: *commonEnv
        volumes:
          - ./OPERATIONAL/acl:/acl
          - ./OPERATIONAL/keys:/pem
        networks:
          - operational_network

networks:
    operational_network:
        name: operational_network
        driver: bridge

volumes:
    rdbms_staging_data:
    rdbms_dos_data:
