version: '3.6'

x-shared-environment: &commonEnv
    TZ: "America/Mexico_City"
    REDIS_HOST: "cache"
    REDIS_PORT: 6379

services:
    cfdi:
        container_name: 'cfdi'
        build: './DOS/cfdi'
        ports:
          - '8080:8080'
        environment: *commonEnv
        volumes:
          - ./DOS/cfdi/service:/yield
        networks:
          - operational_network
    cache_redis:
        container_name: 'cache_redis'
        image: redis:alpine
        ports:
          - "6379:6379"
        environment: *commonEnv
        networks:
          - operational_network


networks:
    operational_network:
        name: operational_network
        driver: bridge
